version: "2"

services:

  bootnode:

    hostname: bootnode

    environment: 

      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b

    build:

      context: ./bootnode

    ports: 

      - 30301:30301/udp

    networks:

      roomnet: 

        ipv4_address: 172.25.0.101



  node-1:

    hostname: node-1

    depends_on: 

      - bootnode

    environment:

      - address=3590aca93338b0721966a8d0c96ebf2c4c87c544

      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c

      - bootnodeIp=172.25.0.101  

    build: 

      context: ./nodes

      args:

        privatekey: df504d175ae63abf209bad9dda965310d99559620550e74521a6798a41215f46

        password: node-1

    container_name: node-1

    ports:

      - 8545:8545

    volumes:

      - eth-data-1:/root/.ethash

    networks:

      roomnet:

        ipv4_address: 172.25.0.102 # The monitor needs to know this address



  node-2:

    hostname: node-2

    depends_on: 

      - bootnode

    environment:

      - address=8cc5a1a0802db41db826c2fcb72423744338dcb0

      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c

      - bootnodeIp=172.25.0.101

    build: 

      context: ./nodes

      args:

        privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35

        password: node-2

    container_name: node-2

    ports:

      - 8546:8545

    volumes:

     - eth-data-2:/root/.ethash

    networks:

      roomnet:

        ipv4_address: 172.25.0.103



  node-3:

     hostname: node-3

     depends_on: 

       - bootnode

     environment:

       - address=4208e6787feed868dd8e6e36b03d6f44916aa5c6

       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c

       - bootnodeIp=172.25.0.101

     build:

       context: ./nodes

       args:

         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35

         password: node-3

     container_name: node-3

     ports:

       - 8547:8545

     volumes:

      - eth-data-3:/root/.ethash

     networks:

       roomnet:

         ipv4_address: 172.25.0.104



  node-4:

     hostname: node-4

     depends_on: 

       - bootnode

     environment:

       - address=624facb43e49d6572e76b13c6e20efae8cc4c284

       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c

       - bootnodeIp=172.25.0.101

     build:

       context: ./nodes

       args:

         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35

         password: node-4

     container_name: node-4

     ports:

       - 8548:8545

     volumes:

      - eth-data-4:/root/.ethash

     networks:

       roomnet:

         ipv4_address: 172.25.0.105



  node-5:

     hostname: node-5

     depends_on: 

       - bootnode

     environment:

       - address=c5d6bb61cfb4474f7891546d163e6fa76cba0739

       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c

       - bootnodeIp=172.25.0.101

     build:

       context: ./nodes

       args:

         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35

         password: node-5

     container_name: node-5

     ports:

       - 8549:8545

     volumes:

      - eth-data-5:/root/.ethash

     networks:

       roomnet:

         ipv4_address: 172.25.0.106



networks:

  roomnet:

    driver: bridge

    ipam:

      config:

      - subnet: 172.25.0.0/24



volumes:

  eth-data-1:

  eth-data-2:

  eth-data-3:

  eth-data-4:

  eth-data-5: