FROM ubuntu:18.04



MAINTAINER Tamas Kovacs



RUN apt-get update \

     && apt-get install -y wget \

     && rm -rf /var/lib/apt/lists/* 

	 

WORKDIR "/opt"

ARG GETHBINARY="geth-linux-amd64-1.9.7-a718daa6.tar.gz"

RUN wget "https://gethstore.blob.core.windows.net/builds/$GETHBINARY"

RUN tar -xzvf $GETHBINARY --strip 1

RUN rm $GETHBINARY



ADD ./genesis.json ./genesis.json

RUN ./geth init genesis.json



ARG password

ARG privatekey

RUN echo $password > ~/.accountpassword

RUN echo $privatekey > ~/.privatekey

RUN ./geth account import --password ~/.accountpassword  ~/.privatekey



ENV address=""

ENV bootnodeId=""

ENV bootnodeIp=""

CMD exec ./geth --bootnodes "enode://$bootnodeId@$bootnodeIp:30301" --networkid="73459324" --verbosity=4 --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --syncmode=full --mine --etherbase $address --allow-insecure-unlock --unlock $address --password ~/.accountpassword



EXPOSE 8545

EXPOSE 30303